version: '3'
services:
  db:
    image: mysql
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    expose:
      - "3306"
    volumes:
      - ./dockermysql:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=city_house_price
      - MYSQL_ROOT_PASSWORD=root1234
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:9000 --insecure
    volumes:
      - .:/leartd
    ports:
      - "8080:9000"
    depends_on:
      - db
