# Generated by Django 3.2.15 on 2023-01-22 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.district'),
        ),
    ]
