# Generated by Django 3.2.15 on 2023-03-11 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_school_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.district'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.district'),
        ),
    ]
