# Generated by Django 3.2.15 on 2023-03-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20230312_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '无等级'), (2, '一乙'), (3, '一甲'), (4, '二乙'), (5, '二甲'), (6, '三乙'), (7, '三甲'), (9, '其它')]),
        ),
        migrations.AlterField(
            model_name='school',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '幼儿园'), (2, '小学'), (3, '初中'), (4, '职业高中'), (5, '普通高中'), (9, '其它')]),
        ),
    ]
